### PR TITLE
Quick Reorganization

### PR DESCRIPTION
**Pull request by cra0zy**
Few minor files got axed, mostly just moved stuff to "Source" folder (yes, I know "src" sounds nice, but I always feel dirty naming folders with lowercase for c# repos...).

https://github.com/cra0zy/gtk-sharp/tree/reorg to see how it looks.

### CODE REVIEW

**Comment by thiblahute** [comment]
Not sure what happened but it looks like you removed some required files, at least:

- `cairo/cairo-api.xml`
- `glib/glib-api.xml`
- `nuget.py`
- `sample/valtest/valobj-api.xml`

Fixed those here:

https://github.com/thiblahute/gtk-sharp-1/commit/7e1463f866efdb7aa5cd2764635e5f78288d09ed

**Comment by cra0zy** [comment]
I did remove the nuget one, but not the xml ones.

**Comment by cra0zy** [comment]
(nuget files we currently posses are useless)

**Comment by cra0zy** [comment]
@thiblahute .gitignore removed some files, need to manually add them.

**Comment by thiblahute** [comment]
> (nuget files we currently posses are useless)

The `nugget.py` one is mine and is very straight forward to generate several nuggets.

**Comment by cra0zy** [comment]
> The nugget.py one is mine and is very straight forward to generate several nuggets.

We will not be using it.... we need separate nugets and I'll write them and connect them using CAKE once I have time.

**Comment by thiblahute** [comment]
We need a `meson.build` in the main folder so it can be used as subproject.

**Comment by cra0zy** [comment]
> We need a meson.build in the main folder so it can be used as subproject.

I would have moved it to the main folder, but than some paths in meson files would need to be fixed... can you merge this and submit a PR which moves meson.build to the main folder?

**Pull request merged**
